// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCartItem = "cart_items"

// CartItem mapped from table <cart_items>
type CartItem struct {
	ProductID int64 `gorm:"column:product_id;primaryKey" json:"product_id"`
	Quantity  int64 `gorm:"column:quantity;not null" json:"quantity"`
}

// TableName CartItem's table name
func (*CartItem) TableName() string {
	return TableNameCartItem
}
