// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePaymentDetail = "payment_details"

// PaymentDetail mapped from table <payment_details>
type PaymentDetail struct {
	PaymentID  int64  `gorm:"column:payment_id;primaryKey;autoIncrement:true" json:"payment_id"`
	OrderID    int64  `gorm:"column:order_id;not null" json:"order_id"`
	CardNumber string `gorm:"column:card_number;not null" json:"card_number"`
	ExpiryDate string `gorm:"column:expiry_date;not null" json:"expiry_date"`
	Cvv        string `gorm:"column:cvv;not null" json:"cvv"`
}

// TableName PaymentDetail's table name
func (*PaymentDetail) TableName() string {
	return TableNamePaymentDetail
}
