// Code generated by hertz generator.

package product

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/hewo/tik-shop/route/biz/router/hewo/tikshop/route/common"
	"github.com/hewo/tik-shop/shared/consts"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproductMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.RoleAdmin, consts.RoleMerchant),
	}
}

func _productMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproductMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _modifystockMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _productsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _products0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproductbyidMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.RoleAdmin, consts.RoleMerchant),
	}
}

func _modifystockbyidMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.RoleAdmin, consts.RoleMerchant),
	}
}

func _getproductbyidMw() []app.HandlerFunc {
	return nil
}

func _updateproductbyidMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		common.PasetoAuth(consts.RoleAdmin, consts.RoleMerchant),
	}
}
