// Code generated by hertz generator.

package order

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	base "github.com/hewo/tik-shop/route/biz/model/hewo/tikshop/route/base"
	order "github.com/hewo/tik-shop/route/biz/model/hewo/tikshop/route/order"
)

// GetOrders .
// @Summary GetOrders
// @Description 获取订单列表，支持分页和过滤。
// @Tags order
// @Accept json
// @Produce json
// @Param request query order.GetOrdersRequest true "Query parameters for filtering and pagination"
// @Success 200 {array} base.Order "List of orders"
// @Failure 400 {string} string "Invalid request"
// @router /api/orders [GET]
func GetOrders(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.GetOrdersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new([]*base.Order)

	c.JSON(consts.StatusOK, resp)
}

// GetOrderInfo .
// @Summary GetOrderInfo
// @Description 根据订单 ID 获取订单的详细信息。
// @Tags order
// @Accept json
// @Produce json
// @Param orderId path string true "Order ID"
// @Param request query order.GetOrderInfoRequest true "Query parameters for order details"
// @Success 200 {object} base.Order "Order details"
// @Failure 400 {string} string "Invalid request"
// @router /api/order/:orderId [GET]
func GetOrderInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.GetOrderInfoRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.Order)

	c.JSON(consts.StatusOK, resp)
}

// PostOrder .
// @Summary PostOrder
// @Description 创建一个新的订单，包括订单的详细信息。
// @Tags order
// @Accept json
// @Produce json
// @Param request body order.PostOrderRequest true "Order details for creation"
// @Success 200 {object} order.PostOrderResponse "Order created successfully"
// @Failure 400 {string} string "Invalid request"
// @router /api/order [POST]
func PostOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.PostOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.PostOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// PayOrder .
// @Summary PayOrder
// @Description 根据订单 ID 支付订单。
// @Tags order
// @Accept json
// @Produce json
// @Param orderId path string true "Order ID"
// @Param request body order.PayOrderRequest true "Payment details for the order"
// @Success 200 {object} base.MessageResponse "Payment successful"
// @Failure 400 {string} string "Invalid request"
// @router /api/order/:orderId/pay [POST]
func PayOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.PayOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.MessageResponse)

	c.JSON(consts.StatusOK, resp)
}

// CancelOrder .
// @Summary CancelOrder
// @Description 根据订单 ID 取消订单。
// @Tags order
// @Accept json
// @Produce json
// @Param orderId path string true "Order ID"
// @Param request body order.CancelOrderRequest true "Details for canceling the order"
// @Success 200 {object} base.MessageResponse "Order canceled successfully"
// @Failure 400 {string} string "Invalid request"
// @router /api/orders/:orderId/cancel [POST]
func CancelOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.CancelOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.MessageResponse)

	c.JSON(consts.StatusOK, resp)
}

// PlaceOrder .
// @router /order [POST]
func PlaceOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.CreateOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.CreateOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// ListOrders .
// @router /order [GET]
func ListOrders(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.ListOrdersRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.ListOrdersResponse)

	c.JSON(consts.StatusOK, resp)
}

// GetOrder .
// @router /order/:id [GET]
func GetOrder(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.GetOrderRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.GetOrderResponse)

	c.JSON(consts.StatusOK, resp)
}

// MarkOrderPaid .
// @router /order/:id/mark_paid [POST]
func MarkOrderPaid(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order.MarkOrderPaidRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(order.MarkOrderPaidResponse)

	c.JSON(consts.StatusOK, resp)
}
