// Code generated by hertz generator.

package cart

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	cartrpc "github.com/hewo/tik-shop/kitex_gen/hewo/tikshop/cart"
	base "github.com/hewo/tik-shop/route/biz/model/hewo/tikshop/route/base"
	cart "github.com/hewo/tik-shop/route/biz/model/hewo/tikshop/route/cart"
	"github.com/hewo/tik-shop/route/init/rpc"
)

// GetCart .
// @router /api/cart [GET]
func GetCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.GetCartRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	res, err := rpc.CartClient.GetCart(ctx, cartrpc.NewGetCartRequest())
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
	}
	resp := make([]*base.CartItem, len(res.Items))

	for i, v := range res.Items {
		resp[i] = &base.CartItem{
			ProductId: v.ProductId,
			Quantity:  v.Quantity,
		}
	}

	c.JSON(consts.StatusOK, resp)
}

// AddToCart .
// @router /api/cart [POST]
func AddToCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.AddToCartRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.MessageResponse)

	c.JSON(consts.StatusOK, resp)
}

// UpdateCartItem .
// @router /api/cart/:productId [PUT]
func UpdateCartItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.UpdateCartItemRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.MessageResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteCartItem .
// @router /api/cart/:productId [DELETE]
func DeleteCartItem(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.DeleteCartItemRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.MessageResponse)

	c.JSON(consts.StatusOK, resp)
}

// DeleteCart .
// @router /api/cart [DELETE]
func DeleteCart(ctx context.Context, c *app.RequestContext) {
	var err error
	var req cart.DeleteCartRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(base.MessageResponse)

	c.JSON(consts.StatusOK, resp)
}
