// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "TikShop 开发团队",
            "url": "https://github.com/hewo/tik-shop"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/admin/login": {
            "post": {
                "responses": {}
            }
        },
        "/api/auth/login": {
            "post": {
                "responses": {}
            }
        },
        "/api/auth/verify": {
            "get": {
                "responses": {}
            }
        },
        "/api/cart": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/cart/:productId": {
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/order": {
            "post": {
                "responses": {}
            }
        },
        "/api/order/:orderId": {
            "get": {
                "responses": {}
            }
        },
        "/api/order/:orderId/pay": {
            "post": {
                "responses": {}
            }
        },
        "/api/orders": {
            "get": {
                "responses": {}
            }
        },
        "/api/orders/:orderId/cancel": {
            "post": {
                "responses": {}
            }
        },
        "/api/product/:id": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            },
            "delete": {
                "responses": {}
            }
        },
        "/api/products": {
            "get": {
                "responses": {}
            },
            "post": {
                "responses": {}
            }
        },
        "/api/user/:id": {
            "get": {
                "responses": {}
            },
            "put": {
                "responses": {}
            }
        },
        "/api/user/:id/password": {
            "put": {
                "responses": {}
            }
        },
        "/api/user/register": {
            "post": {
                "responses": {}
            }
        },
        "/ping": {
            "get": {
                "description": "用于测试服务器是否正常响应，返回 \"pong\" 消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "测试接口",
                "responses": {
                    "200": {
                        "description": "返回 message: pong 的 JSON 响应",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8888",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "TikShop API",
	Description:      "TikShop 的 API 服务，用于处理相关业务逻辑。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
