// Code generated by hertz generator.

package order

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _postorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _payorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ordersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getordersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _orderid0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cancelorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _order0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listordersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getorderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _markorderpaidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _placeorderMw() []app.HandlerFunc {
	// your code...
	return nil
}
